name: GitHub Metrics
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Bangkah
          template: terminal
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
